### ISSUE TITLE
In eOSD, krono-safe URLs are incorrects

### ISSUE THREAD

**Issue by fabiensiron** [krono-safe/eosd#2]
In the following files, krono-safe URLs are of the form "www.kronosafe.com/oa[s]d", this should be "www.krono-safe.com/...":

- plugins/com.kronosafe.osd/plugin.xml
- examples/com.kronosafe.osd.examples.aadl2osd/sample/launch/aadl2osd.launch
- plugins/com.kronosafe.osd.edit/plugin.xml
- examples/com.kronosafe.osd.examples.aadl2osd/sample/transformation/aadl2osd.atl
- plugins/com.kronosafe.osd.design/description/osd.odesign
- plugins/com.kronosafe.osd/model/osd.ecore
- plugins/com.kronosafe.osd/model/osd.html

**Comment by fthomasfr** [comment]
OSD metamodel URLs have been changed in commit https://github.com/krono-safe/eosd/pull/3/commits/e0acf35339569814424303dfc369fdf515fc73da proposed in pull request #3

New URLs are www.krono-safe.com/...

Nevertheless, plugin directories cannot change because of Java restriction about package names: without "-" in names.
